version: '3.6'

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.8.2
  INSTALL_NODE_VERSION: 12

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules
    - ./dev.db:/tmp/dev.db

services:
  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "airscore-development"
    container_name: flask_dev
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
      - "2992:2992"
    environment:
      REDIS_URL: ${REDIS_CONTAINER}://${REDIS_CONTAINER}:6379
      REDIS_CONTAINER: ${REDIS_CONTAINER}
      WEB_SERVER_CONTAINER: ${WEB_SERVER_CONTAINER}
      FLASK_CONTAINER: flask_dev
      FLASK_PORT: ${FLASK_PORT}
      FLASK_ENV: development
      FLASK_DEBUG: 1
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USE_TLS: ${MAIL_USE_TLS}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      ADMINS: ${ADMINS}
      MYSQLHOST: ${MYSQLHOST}
      DATABASE: ${DATABASE}
      MYSQLUSER: ${MYSQLUSER}
      MYSQLPASSWORD: ${MYSQLPASSWORD}
      XCONTEST_USER: ${XCONTEST_USER}
      XCONTEST_PASS: ${XCONTEST_PASS}
      TELEGRAM_API: ${TELEGRAM_API}
      TELEGRAM_CHANNEL: ${TELEGRAM_CHANNEL}
    <<: *default_volumes

  manage:
    build:
      context: .
      target: manage
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      REDIS_URL: redis://redis:6379
      REDIS_CONTAINER: redis
      WEB_SERVER_CONTAINER: dummy
      FLASK_CONTAINER: flask_dev
      FLASK_PORT: 3214
      MAIL_SERVER: dummy
      MAIL_PORT: 123
      MAIL_USE_TLS: dummy
      MAIL_USERNAME: dummy
      MAIL_PASSWORD: dummy
      ADMINS: dummy
      MYSQLHOST: dummy
      DATABASE: dummy
      MYSQLUSER: dummy
      MYSQLPASSWORD: dummy
      XCONTEST_USER: dummy
      XCONTEST_PASS: dummy
      TELEGRAM_API: dummy
      TELEGRAM_CHANNEL: dummy
    image: "airscore-manage"
    container_name: manage
    stdin_open: true
    tty: true
    <<: *default_volumes

  redis:
    image: redis
    container_name: ${REDIS_CONTAINER}

volumes:
  node-modules:
  static-build:
  dev-db:
